model:
  in_channels: 3
  num_hidden: 256
  num_res_layers: 2
  embedding_dim: 256
  num_embeddings: 512
  commitment_cost: 1
  saved_models_dir: trained_models_imagenet/
  checkpoint: None
  rng: 313
  decay: 0.99

pixelcnn:
  in_channels: 128
  out_channels: 128
  num_features: 64
  num_layers: 15
  conditional: True
  num_classes: 10
  saved_models_dir: trained_prior/
  base_model_checkpoint: trained_models_imagenet/epoch_29

train:
  batch_size: 32
  num_training_updates: 25000 
  learning_rate: 2.0e-4
  weight_decay: 0
  decay: 0.99 # For VQ with EMA (to be implemented later)
  num_epochs: 40
  save_param_step_interval: 5
  logger_step_interval: 100
  solver: adam

val:
  batch_size: 32

monitor:
  path: tmp.monitor_imagenet/
  train_loss: Training loss 
  train_recon: Training reconstructions

dataset:
  name: imagenet
  train_size: 50000
  val_size: 10000
  path: /net/fs1.ubiq.sony.co.jp/Data1/sDeep/Data/Dataset/ImageNet/original
  dali_threads: 4


extension_module: cudnn
device_id: '0'
